apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
    - port: 9022
      protocol: TCP
      targetPort: 22
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sonarqube-app
