apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
      name: sonarservice
    - port: 22
      protocol: TCP
      targetPort: 22
      name: sonarssh
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: terminalport
    - port: 5000
      protocol: TCP
      targetPort: 5000
      name: apiserver
  selector:
    app: sonarqube-app
